// Precompute a real dotted world map (via `dotted-map`, which uses actual
// country geometry) into a static data module so the bundle stays light and
// node pins align exactly to the dot grid.
import pkg from 'dotted-map'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { flowNodes } from '../src/data/network.js'

const DottedMap = pkg.default || pkg
const __dirname = dirname(fileURLToPath(import.meta.url))

const map = new DottedMap({ height: 60, grid: 'diagonal' })

// viewBox from a throwaway getSVG
const svg = map.getSVG({ radius: 0.3, color: '#000', shape: 'circle' })
const viewBox = svg.match(/viewBox="([^"]+)"/)[1]

// all land dots
const dots = Object.values(map.points).map((p) => [
  Math.round(p.x * 10) / 10,
  Math.round(p.y * 10) / 10,
])

// node pin positions, keyed by id, aligned to the same grid
const pins = {}
for (const n of flowNodes) {
  const pin = map.getPin({ lat: n.lat, lng: n.lng })
  pins[n.id] = [Math.round(pin.x * 100) / 100, Math.round(pin.y * 100) / 100]
}

const out = `// AUTO-GENERATED by scripts/genmap.mjs — do not edit by hand.
// Real dotted world map (country geometry) from the \`dotted-map\` package.
export const viewBox = '${viewBox}'
export const dots = ${JSON.stringify(dots)}
export const pins = ${JSON.stringify(pins)}
`

const dest = resolve(__dirname, '../src/data/worldmap.js')
writeFileSync(dest, out)
console.log(`wrote ${dest} — ${dots.length} dots, ${Object.keys(pins).length} pins, viewBox ${viewBox}`)
